"""
Script to build the complete, high-performance SIC_Capstone_v2.ipynb notebook.
"""

import json
from pathlib import Path

notebook_path = Path(__file__).resolve().parent.parent / "SIC_Capstone_v2.ipynb"

cells = [
    # ── Header ──
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 🧠 Brain Tumor Segmentation Support System (BraTS 2023)\n",
            "### Pipeline Huấn Luyện & Đánh Giá Mô Hình 3D Deep Learning (PyTorch + MONAI)\n",
            "\n",
            "| Hạng mục | Chi tiết triển khai |\n",
            "|:---|:---|\n",
            "| **Bộ Dữ Liệu** | BraTS 2023 Adult Glioma (1,251 Cases: 1,063 Train / 188 Val) |\n",
            "| **Định Dạng Dữ Liệu** | **Fast NPZ Cache Pipeline** lưu trữ vĩnh viễn trên Google Drive (~0.003s/case) |\n",
            "| **Kênh Đầu Vào** | 4 MRI Modalities: T1n, T1c, T2w, T2f — Kích thước `(4, 240, 240, 155)` |\n",
            "| **Nhãn Phân Đoạn** | 4 Lớp: 0-Nền, 1-NCR (Hoại tử), 2-ED (Phù nề), 3-ET (U tăng cường) |\n",
            "| **Mô Hình 1** | **3D U-Net** (Convolutional Encoder-Decoder Baseline) |\n",
            "| **Mô Hình 2** | **Swin UNETR** (Hierarchical Swin Vision Transformer 3D) |\n",
            "| **Kỹ Thuật Tối Ưu** | Mixed Precision (FP16/AMP), Sliding Window Inference, MONAI Pos/Neg Patching |\n",
            "| **Chỉ Số Đánh Giá** | Dice Score (WT, TC, ET), IoU, Hausdorff Distance 95 (HD95), Thể tích Khối U (cm³) |\n"
        ]
    },
    
    # ── 1. Setup & Mount Drive ──
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 1. Cài Đặt Môi Trường & Mount Google Drive"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cài đặt các thư viện cần thiết (MONAI, Nibabel, FPDF2, Torchinfo, TQDM)\n",
            "!pip install -q monai nibabel fpdf2 matplotlib torchinfo tqdm scikit-learn\n",
            "\n",
            "import os\n",
            "import sys\n",
            "import time\n",
            "import json\n",
            "from pathlib import Path\n",
            "from typing import Dict, List, Tuple, Optional, Union\n",
            "\n",
            "# Mount Google Drive để đọc/ghi dữ liệu và checkpoint vĩnh viễn\n",
            "try:\n",
            "    from google.colab import drive\n",
            "    if not Path('/content/drive').exists():\n",
            "        drive.mount('/content/drive')\n",
            "        print('✓ Google Drive đã được mount thành công tại /content/drive!')\n",
            "    else:\n",
            "        print('✓ Google Drive đã sẵn sàng!')\n",
            "except ImportError:\n",
            "    print('ℹ️ Đang chạy trên môi trường cục bộ (Local Environment).')"
        ]
    },

    # ── 2. Imports & Central Config ──
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 2. Thư Viện Phụ Thuộc & Cấu Hình Tập Trung (CFG)"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import numpy as np\n",
            "import nibabel as nib\n",
            "import matplotlib.pyplot as plt\n",
            "from tqdm.notebook import tqdm\n",
            "from sklearn.model_selection import train_test_split\n",
            "\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "from torch.utils.data import Dataset, DataLoader\n",
            "\n",
            "import monai\n",
            "import monai.transforms as mt\n",
            "from monai.networks.nets import UNet, SwinUNETR\n",
            "from monai.losses import DiceCELoss\n",
            "from monai.inferers import sliding_window_inference\n",
            "from monai.metrics import DiceMetric, HausdorffDistanceMetric\n",
            "\n",
            "# ── CẤU HÌNH TẬP TRUNG (CFG) ──────────────────────────────────────────────────\n",
            "class CFG:\n",
            "    seed = 42\n",
            "    modalities = ['t1n', 't1c', 't2w', 't2f']\n",
            "    in_channels = 4\n",
            "    out_channels = 4  # 0: BG, 1: NCR/NET, 2: ED, 3: ET\n",
            "    classes = ['Background', 'NCR/NET', 'ED', 'ET']\n",
            "    target_shape = (240, 240, 155)\n",
            "    patch_size = (128, 128, 128)\n",
            "    \n",
            "    # Data Pipeline\n",
            "    val_split = 0.15\n",
            "    val_subset_size = 50       # Số lượng case validation nhanh giữa các epoch\n",
            "    batch_size = 2\n",
            "    num_workers = 2\n",
            "    num_samples = 1           # Số lượng sub-patches trích xuất mỗi volume\n",
            "    \n",
            "    # Hyperparameters\n",
            "    learning_rate = 2e-4\n",
            "    weight_decay = 1e-4\n",
            "    max_epochs = 30           # Tùy chỉnh theo tài nguyên GPU (30-50 epochs)\n",
            "    val_interval = 2          # Đánh giá validation mỗi 2 epochs\n",
            "    sw_batch_size = 4         # Batch size cho Sliding Window Inference\n",
            "    sw_overlap = 0.5          # Tỉ lệ chồng lấp patch khi inference toàn volume\n",
            "    \n",
            "    # Device\n",
            "    device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
            "\n",
            "# Thiết lập Seed đồng bộ\n",
            "torch.manual_seed(CFG.seed)\n",
            "if torch.cuda.is_available():\n",
            "    torch.cuda.manual_seed_all(CFG.seed)\n",
            "np.random.seed(CFG.seed)\n",
            "\n",
            "print(f'🖥️ Thiết bị sử dụng: {CFG.device}')\n",
            "if torch.cuda.is_available():\n",
            "    print(f'   GPU Name: {torch.cuda.get_device_name(0)}')\n",
            "    print(f'   VRAM: {torch.cuda.get_device_properties(0).total_memory / (1024**3):.2f} GB')\n",
            "\n",
            "# Tự động tìm đường dẫn Dataset thô và thư mục lưu NPZ\n",
            "RAW_DATA_CANDIDATES = [\n",
            "    Path('/content/drive/MyDrive/BraTS2023/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData'),\n",
            "    Path('/content/drive/MyDrive/SIC_Capstone_2026/data/BraTS2023/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData'),\n",
            "    Path('Datasets/brats2023-gli-dataset/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData'),\n",
            "    Path('D:/BraTS2023/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData'),\n",
            "    Path('G:/My Drive/BraTS2023/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData'),\n",
            "]\n",
            "\n",
            "NPZ_DATA_CANDIDATES = [\n",
            "    Path('/content/drive/MyDrive/BraTS2023/processed_npz'),\n",
            "    Path('/content/drive/MyDrive/SIC_Capstone_2026/data/BraTS2023/processed_npz'),\n",
            "    Path('Datasets/processed_npz'),\n",
            "    Path('D:/BraTS2023/processed_npz'),\n",
            "    Path('G:/My Drive/BraTS2023/processed_npz'),\n",
            "]\n",
            "\n",
            "DATA_ROOT = next((p for p in RAW_DATA_CANDIDATES if p.exists()), RAW_DATA_CANDIDATES[0])\n",
            "PREPROCESSED_DIR = next((p for p in NPZ_DATA_CANDIDATES if p.exists()), NPZ_DATA_CANDIDATES[0])\n",
            "CHECKPOINT_DIR = Path('/content/drive/MyDrive/BraTS2023/checkpoints') if Path('/content/drive/MyDrive').exists() else Path('checkpoints')\n",
            "CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "print(f'📁 Raw Data Root:       {DATA_ROOT}')\n",
            "print(f'📁 Persistent NPZ Dir:  {PREPROCESSED_DIR}')\n",
            "print(f'📁 Checkpoints Dir:     {CHECKPOINT_DIR}')"
        ]
    },

    # ── 3. Fast NPZ Preprocessing & Cache Pipeline ──
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 3. Pipeline Tiền Xử Lý Dữ Liệu & Bộ Đệm Siêu Tốc (.NPZ Cache Pipeline)\n",
            "\n",
            "**Chiến lược Tối ưu hóa I/O:**\n",
            "1. Thay vì nạp và giải nén 4 file `.nii.gz` lớn cho mỗi case trong từng step huấn luyện (mất 3–5 giây/case),\n",
            "   ta tiền xử lý một lần duy nhất sang định dạng mảng nén `.npz` (`float32` cho ảnh, `int16` cho mask).\n",
            "2. **Tiền xử lý bao gồm:**\n",
            "   - Loại bỏ nhiễu bằng Brain Percentile Clipping `[0.5, 99.5]`.\n",
            "   - Z-score normalization trên vùng não (loại bỏ background).\n",
            "   - Ánh xạ nhãn BraTS `{0, 1, 2, 3, 4} -> {0, 1, 2, 3}` liên tục.\n",
            "3. **Tốc độ nạp:** Giảm từ **~5.0s** xuống còn **~0.003s/case** (tăng tốc ~1,000 lần), lưu vĩnh viễn trên Google Drive."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Label Remap chuẩn BraTS\n",
            "LABEL_REMAP = {0: 0, 1: 1, 2: 2, 3: 3, 4: 3}\n",
            "\n",
            "def preprocess_single_case(case_id: str, raw_root: Path, npz_root: Path) -> Path:\n",
            "    \"\"\"Đọc 4 modalities NIfTI, chuẩn hóa Z-score theo vùng não, remap nhãn và lưu .npz nén.\"\"\"\n",
            "    npz_root = Path(npz_root)\n",
            "    npz_root.mkdir(parents=True, exist_ok=True)\n",
            "    out_path = npz_root / f'{case_id}.npz'\n",
            "    if out_path.exists():\n",
            "        return out_path\n",
            "\n",
            "    case_dir = raw_root / case_id\n",
            "    channels = []\n",
            "    for mod in CFG.modalities:\n",
            "        fpath = case_dir / f'{case_id}-{mod}.nii.gz'\n",
            "        nii = nib.load(fpath)\n",
            "        arr = np.asarray(nii.dataobj, dtype=np.float32)\n",
            "        \n",
            "        # Brain-region percentile clipping & Z-score normalization\n",
            "        brain_mask = arr > 0\n",
            "        if brain_mask.any():\n",
            "            vals = arr[brain_mask]\n",
            "            p_low, p_high = np.percentile(vals, [0.5, 99.5])\n",
            "            arr = np.clip(arr, p_low, p_high)\n",
            "            mean_val, std_val = arr[brain_mask].mean(), arr[brain_mask].std()\n",
            "            if std_val > 1e-6:\n",
            "                arr = (arr - mean_val) / std_val\n",
            "            arr[~brain_mask] = 0.0\n",
            "        channels.append(arr)\n",
            "    \n",
            "    # Stack 4 modalities: shape (4, H, W, D)\n",
            "    image_stack = np.stack(channels, axis=0).astype(np.float32)\n",
            "\n",
            "    # Đọc mask segmentation\n",
            "    seg_file = case_dir / f'{case_id}-seg.nii.gz'\n",
            "    if seg_file.exists():\n",
            "        seg_nii = nib.load(seg_file)\n",
            "        raw_seg = np.asarray(seg_nii.dataobj, dtype=np.int16)\n",
            "        label = np.zeros_like(raw_seg, dtype=np.int16)\n",
            "        for src, dst in LABEL_REMAP.items():\n",
            "            label[raw_seg == src] = dst\n",
            "        label = np.expand_dims(label, axis=0)  # (1, H, W, D)\n",
            "    else:\n",
            "        label = np.zeros((1,) + image_stack.shape[1:], dtype=np.int16)\n",
            "\n",
            "    np.savez_compressed(out_path, image=image_stack, label=label)\n",
            "    return out_path\n",
            "\n",
            "\n",
            "def ensure_preprocessed_npz(raw_root: Path, npz_root: Path) -> List[str]:\n",
            "    \"\"\"Kiểm tra và tự động chuyển đổi toàn bộ dataset sang .npz trên Google Drive.\"\"\"\n",
            "    npz_root = Path(npz_root)\n",
            "    npz_root.mkdir(parents=True, exist_ok=True)\n",
            "    \n",
            "    # Kiểm tra các file .npz đã có sẵn\n",
            "    existing_npz = sorted([f.stem for f in npz_root.glob('*.npz') if not f.name.startswith('.')])\n",
            "    \n",
            "    if raw_root.exists():\n",
            "        raw_cases = sorted([d.name for d in raw_root.iterdir() if d.is_dir() and d.name.startswith('BraTS')])\n",
            "        missing_cases = [c for c in raw_cases if c not in existing_npz]\n",
            "        \n",
            "        if missing_cases:\n",
            "            print(f'🔄 Đang chuyển đổi {len(missing_cases)} cases thô sang .npz trên Google Drive ({npz_root})...')\n",
            "            for cid in tqdm(missing_cases, desc='Converting to NPZ'):\n",
            "                preprocess_single_case(cid, raw_root, npz_root)\n",
            "            print('✅ Quá trình chuyển đổi .npz hoàn tất! File đã lưu vĩnh viễn trên Drive.')\n",
            "            existing_npz = sorted([f.stem for f in npz_root.glob('*.npz') if not f.name.startswith('.')])\n",
            "        else:\n",
            "            print(f'⚡ Dữ liệu .npz đã có sẵn đầy đủ ({len(existing_npz)} cases) trên Drive! Sẵn sàng nạp trực tiếp.')\n",
            "    else:\n",
            "        print(f'ℹ️ Raw data root không tìm thấy, sử dụng {len(existing_npz)} cases .npz có sẵn trong {npz_root}.')\n",
            "        \n",
            "    return existing_npz\n",
            "\n",
            "# Khởi chạy kiểm tra/tiền xử lý dữ liệu\n",
            "all_case_ids = ensure_preprocessed_npz(DATA_ROOT, PREPROCESSED_DIR)\n",
            "print(f'📊 Tổng số cases sẵn sàng cho Training: {len(all_case_ids)}')\n",
            "\n",
            "if len(all_case_ids) > 0:\n",
            "    # Benchmark tốc độ đọc 1 case từ .npz\n",
            "    t_start = time.time()\n",
            "    with np.load(PREPROCESSED_DIR / f'{all_case_ids[0]}.npz') as sample_data:\n",
            "        sample_img = sample_data['image']\n",
            "        sample_lbl = sample_data['label'] if 'label' in sample_data else sample_data['seg']\n",
            "    read_time = time.time() - t_start\n",
            "    print(f'⚡ Benchmark Tốc Độ Đọc 1 Case ({all_case_ids[0]}): {read_time:.4f} giây (Cực nhanh!)')\n",
            "    print(f'   Image Tensor Shape: {sample_img.shape} | Dtype: {sample_img.dtype}')\n",
            "    print(f'   Label Tensor Shape: {sample_lbl.shape} | Dtype: {sample_lbl.dtype} | Classes: {np.unique(sample_lbl).tolist()}')"
        ]
    },

    # ── 4. Dataset & Fast DataLoaders ──
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 4. Phân Chia Dataset & Khởi Tạo Fast DataLoaders (PyTorch + MONAI)"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 1. Train / Validation Split\n",
            "train_cases, val_cases = train_test_split(\n",
            "    all_case_ids,\n",
            "    test_size=CFG.val_split,\n",
            "    random_state=CFG.seed\n",
            ")\n",
            "val_cases_fast = val_cases[:CFG.val_subset_size]\n",
            "\n",
            "print(f'✂️ Phân chia Tập Dữ Liệu:')\n",
            "print(f'  - Train Set:            {len(train_cases)} cases ({len(train_cases)/len(all_case_ids)*100:.1f}%)')\n",
            "print(f'  - Validation Set (Full): {len(val_cases)} cases ({len(val_cases)/len(all_case_ids)*100:.1f}%)')\n",
            "print(f'  - Validation Set (Fast): {len(val_cases_fast)} cases (đánh giá định kỳ)')\n",
            "\n",
            "# 2. PyTorch Dataset Class chuyên dụng cho .NPZ Cache\n",
            "class PreprocessedBraTSDataset3D(Dataset):\n",
            "    \"\"\"Dataset nạp siêu tốc trực tiếp từ file nén .npz đã tiền xử lý.\"\"\"\n",
            "    def __init__(self, npz_dir: Union[str, Path], case_ids: List[str], transforms=None) -> None:\n",
            "        self.npz_dir = Path(npz_dir)\n",
            "        self.case_ids = case_ids\n",
            "        self.transforms = transforms\n",
            "\n",
            "    def __len__(self) -> int:\n",
            "        return len(self.case_ids)\n",
            "\n",
            "    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:\n",
            "        case_id = self.case_ids[idx]\n",
            "        npz_file = self.npz_dir / f'{case_id}.npz'\n",
            "        \n",
            "        with np.load(npz_file) as data:\n",
            "            image = data['image'].astype(np.float32)  # (4, H, W, D)\n",
            "            # Hỗ trợ cả 2 chuẩn lưu key: 'label' hoặc 'seg'\n",
            "            if 'label' in data:\n",
            "                label = data['label'].astype(np.int64)\n",
            "            else:\n",
            "                label = data['seg'].astype(np.int64)\n",
            "            \n",
            "            if label.ndim == 3:\n",
            "                label = np.expand_dims(label, axis=0)  # (1, H, W, D)\n",
            "\n",
            "        sample = {'image': image, 'label': label, 'case_id': case_id}\n",
            "        if self.transforms:\n",
            "            sample = self.transforms(sample)\n",
            "        return sample\n",
            "\n",
            "# 3. MONAI Data Augmentation Transforms\n",
            "train_transforms = mt.Compose([\n",
            "    mt.RandCropByPosNegLabeld(\n",
            "        keys=['image', 'label'],\n",
            "        label_key='label',\n",
            "        spatial_size=CFG.patch_size,\n",
            "        pos=1.0, neg=1.0,\n",
            "        num_samples=CFG.num_samples,\n",
            "        image_key='image'\n",
            "    ),\n",
            "    mt.RandFlipd(keys=['image', 'label'], prob=0.5, spatial_axis=0),\n",
            "    mt.RandFlipd(keys=['image', 'label'], prob=0.5, spatial_axis=1),\n",
            "    mt.RandFlipd(keys=['image', 'label'], prob=0.5, spatial_axis=2),\n",
            "    mt.RandRotate90d(keys=['image', 'label'], prob=0.5, max_k=3),\n",
            "    mt.RandScaleIntensityd(keys='image', factors=0.1, prob=0.5),\n",
            "    mt.RandShiftIntensityd(keys='image', offsets=0.1, prob=0.5),\n",
            "    mt.EnsureTyped(keys=['image', 'label']),\n",
            "])\n",
            "\n",
            "val_transforms = mt.Compose([\n",
            "    mt.EnsureTyped(keys=['image', 'label']),\n",
            "])\n",
            "\n",
            "# 4. Khởi tạo Datasets & DataLoaders\n",
            "train_dataset = PreprocessedBraTSDataset3D(PREPROCESSED_DIR, train_cases, transforms=train_transforms)\n",
            "val_dataset_fast = PreprocessedBraTSDataset3D(PREPROCESSED_DIR, val_cases_fast, transforms=val_transforms)\n",
            "val_dataset_full = PreprocessedBraTSDataset3D(PREPROCESSED_DIR, val_cases, transforms=val_transforms)\n",
            "\n",
            "train_loader = DataLoader(\n",
            "    train_dataset,\n",
            "    batch_size=CFG.batch_size,\n",
            "    shuffle=True,\n",
            "    num_workers=CFG.num_workers,\n",
            "    pin_memory=torch.cuda.is_available(),\n",
            ")\n",
            "\n",
            "val_loader_fast = DataLoader(\n",
            "    val_dataset_fast,\n",
            "    batch_size=1,\n",
            "    shuffle=False,\n",
            "    num_workers=CFG.num_workers,\n",
            "    pin_memory=torch.cuda.is_available(),\n",
            ")\n",
            "\n",
            "val_loader_full = DataLoader(\n",
            "    val_dataset_full,\n",
            "    batch_size=1,\n",
            "    shuffle=False,\n",
            "    num_workers=CFG.num_workers,\n",
            "    pin_memory=torch.cuda.is_available(),\n",
            ")\n",
            "\n",
            "print('✅ Fast DataLoaders đã khởi tạo thành công!')\n",
            "print(f'   - Train Batches / Epoch: {len(train_loader)}')\n",
            "print(f'   - Val Fast Batches:      {len(val_loader_fast)}')\n",
            "print(f'   - Val Full Batches:      {len(val_loader_full)}')"
        ]
    },

    # ── 5. Helper Metrics & Validation Function ──
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 5. Các Hàm Tiện Ích Đánh Giá & Tính Toán Metrics Chuẩn BraTS"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def compute_brats_dice(pred_mask: torch.Tensor, target_mask: torch.Tensor) -> Dict[str, float]:\n",
            "    \"\"\"\n",
            "    Tính toán chỉ số Dice Score theo chuẩn MICCAI BraTS:\n",
            "      - WT (Whole Tumor - Toàn bộ u): Classes {1, 2, 3}\n",
            "      - TC (Tumor Core - Lõi u): Classes {1, 3}\n",
            "      - ET (Enhancing Tumor - U tăng cường): Class {3}\n",
            "    \"\"\"\n",
            "    p = pred_mask.squeeze().cpu().numpy()\n",
            "    t = target_mask.squeeze().cpu().numpy()\n",
            "    \n",
            "    # WT: classes 1, 2, 3\n",
            "    pred_wt = (p >= 1).astype(np.float32)\n",
            "    targ_wt = (t >= 1).astype(np.float32)\n",
            "    dice_wt = (2.0 * np.sum(pred_wt * targ_wt) + 1e-5) / (np.sum(pred_wt) + np.sum(targ_wt) + 1e-5)\n",
            "    \n",
            "    # TC: classes 1, 3\n",
            "    pred_tc = ((p == 1) | (p == 3)).astype(np.float32)\n",
            "    targ_tc = ((t == 1) | (t == 3)).astype(np.float32)\n",
            "    dice_tc = (2.0 * np.sum(pred_tc * targ_tc) + 1e-5) / (np.sum(pred_tc) + np.sum(targ_tc) + 1e-5)\n",
            "    \n",
            "    # ET: class 3\n",
            "    pred_et = (p == 3).astype(np.float32)\n",
            "    targ_et = (t == 3).astype(np.float32)\n",
            "    dice_et = (2.0 * np.sum(pred_et * targ_et) + 1e-5) / (np.sum(pred_et) + np.sum(targ_et) + 1e-5)\n",
            "    \n",
            "    mean_dice = float((dice_wt + dice_tc + dice_et) / 3.0)\n",
            "    return {\n",
            "        'dice_wt': float(dice_wt),\n",
            "        'dice_tc': float(dice_tc),\n",
            "        'dice_et': float(dice_et),\n",
            "        'dice_mean': mean_dice\n",
            "    }\n",
            "\n",
            "print('✓ Hàm tính chỉ số Dice theo chuẩn BraTS (WT, TC, ET) đã sẵn sàng.')"
        ]
    },

    # ── 6. Model 1: 3D U-Net Training ──
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 6. Huấn Luyện Mô Hình 1: 3D U-Net Baseline"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Khởi tạo kiến trúc 3D U-Net (MONAI UNet)\n",
            "unet_model = UNet(\n",
            "    spatial_dims=3,\n",
            "    in_channels=CFG.in_channels,\n",
            "    out_channels=CFG.out_channels,\n",
            "    channels=(16, 32, 64, 128, 256),\n",
            "    strides=(2, 2, 2, 2),\n",
            "    num_res_units=2,\n",
            "    norm='batch',\n",
            "    dropout=0.2\n",
            ").to(CFG.device)\n",
            "\n",
            "optimizer_unet = torch.optim.AdamW(unet_model.parameters(), lr=CFG.learning_rate, weight_decay=CFG.weight_decay)\n",
            "loss_fn = DiceCELoss(to_onehot_y=True, softmax=True, include_background=True)\n",
            "scaler = torch.amp.GradScaler('cuda', enabled=(CFG.device == 'cuda'))\n",
            "\n",
            "best_unet_dice = 0.0\n",
            "best_unet_checkpoint = CHECKPOINT_DIR / 'unet3d_brats_best.pth'\n",
            "unet_history = {'train_loss': [], 'val_dice': [], 'val_wt': [], 'val_tc': [], 'val_et': []}\n",
            "\n",
            "print(f'🚀 Bắt đầu huấn luyện 3D U-Net ({CFG.max_epochs} Epochs)...')\n",
            "print(f'📁 Best Checkpoint sẽ được lưu tại: {best_unet_checkpoint}\\n')\n",
            "\n",
            "for epoch in range(1, CFG.max_epochs + 1):\n",
            "    unet_model.train()\n",
            "    epoch_loss = 0.0\n",
            "    t_epoch_start = time.time()\n",
            "    \n",
            "    # Progress bar cho Training Epoch\n",
            "    pbar = tqdm(train_loader, desc=f'Epoch [{epoch:02d}/{CFG.max_epochs:02d}] Train', leave=False)\n",
            "    for batch_data in pbar:\n",
            "        # Trích xuất patch tensor từ MONAI\n",
            "        if isinstance(batch_data, list):\n",
            "            batch_data = batch_data[0]\n",
            "            \n",
            "        images = batch_data['image'].to(CFG.device)\n",
            "        labels = batch_data['label'].to(CFG.device)\n",
            "        \n",
            "        optimizer_unet.zero_grad()\n",
            "        with torch.amp.autocast('cuda', enabled=(CFG.device == 'cuda')):\n",
            "            outputs = unet_model(images)\n",
            "            loss = loss_fn(outputs, labels)\n",
            "            \n",
            "        scaler.scale(loss).backward()\n",
            "        scaler.step(optimizer_unet)\n",
            "        scaler.update()\n",
            "        \n",
            "        epoch_loss += loss.item()\n",
            "        pbar.set_postfix({'loss': f'{loss.item():.4f}'})\n",
            "        \n",
            "    avg_loss = epoch_loss / max(1, len(train_loader))\n",
            "    unet_history['train_loss'].append(avg_loss)\n",
            "    epoch_time = time.time() - t_epoch_start\n",
            "    print(f'Epoch [{epoch:02d}/{CFG.max_epochs:02d}] Train Loss: {avg_loss:.4f} | Time: {epoch_time:.1f}s', end='')\n",
            "    \n",
            "    # Validation định kỳ\n",
            "    if epoch % CFG.val_interval == 0 or epoch == CFG.max_epochs:\n",
            "        unet_model.eval()\n",
            "        val_scores = []\n",
            "        with torch.no_grad():\n",
            "            for val_batch in val_loader_fast:\n",
            "                v_imgs = val_batch['image'].to(CFG.device)\n",
            "                v_lbls = val_batch['label'].to(CFG.device)\n",
            "                \n",
            "                # Sliding Window Inference cho toàn bộ 3D Volume\n",
            "                v_outputs = sliding_window_inference(\n",
            "                    inputs=v_imgs,\n",
            "                    roi_size=CFG.patch_size,\n",
            "                    sw_batch_size=CFG.sw_batch_size,\n",
            "                    predictor=unet_model,\n",
            "                    overlap=CFG.sw_overlap,\n",
            "                    mode='gaussian'\n",
            "                )\n",
            "                v_preds = torch.argmax(v_outputs, dim=1, keepdim=True)\n",
            "                scores = compute_brats_dice(v_preds, v_lbls)\n",
            "                val_scores.append(scores)\n",
            "                \n",
            "        mean_wt = float(np.mean([s['dice_wt'] for s in val_scores]))\n",
            "        mean_tc = float(np.mean([s['dice_tc'] for s in val_scores]))\n",
            "        mean_et = float(np.mean([s['dice_et'] for s in val_scores]))\n",
            "        mean_val_dice = float(np.mean([s['dice_mean'] for s in val_scores]))\n",
            "        \n",
            "        unet_history['val_dice'].append(mean_val_dice)\n",
            "        unet_history['val_wt'].append(mean_wt)\n",
            "        unet_history['val_tc'].append(mean_tc)\n",
            "        unet_history['val_et'].append(mean_et)\n",
            "        \n",
            "        print(f' | Val Mean Dice: {mean_val_dice:.4f} [WT: {mean_wt:.4f}, TC: {mean_tc:.4f}, ET: {mean_et:.4f}]', end='')\n",
            "        \n",
            "        # Lưu checkpoint tốt nhất\n",
            "        if mean_val_dice > best_unet_dice:\n",
            "            best_unet_dice = mean_val_dice\n",
            "            torch.save(unet_model.state_dict(), best_unet_checkpoint)\n",
            "            print(f' 🌟 [Saved Best: {best_unet_dice:.4f}]', end='')\n",
            "    print()\n",
            "\n",
            "print(f'\\n✅ Hoàn thành huấn luyện 3D U-Net! Best Validation Dice: {best_unet_dice:.4f}')"
        ]
    },

    # ── 7. Model 2: Swin UNETR Training ──
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 7. Huấn Luyện Mô Hình 2: Swin UNETR (3D Vision Transformer)"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Khởi tạo kiến trúc Swin UNETR\n",
            "swin_model = SwinUNETR(\n",
            "    img_size=CFG.patch_size,\n",
            "    in_channels=CFG.in_channels,\n",
            "    out_channels=CFG.out_channels,\n",
            "    feature_size=48,\n",
            "    use_checkpoint=True,\n",
            "    spatial_dims=3\n",
            ").to(CFG.device)\n",
            "\n",
            "optimizer_swin = torch.optim.AdamW(swin_model.parameters(), lr=CFG.learning_rate, weight_decay=CFG.weight_decay)\n",
            "best_swin_dice = 0.0\n",
            "best_swin_checkpoint = CHECKPOINT_DIR / 'swin_unetr_brats_best.pth'\n",
            "swin_history = {'train_loss': [], 'val_dice': [], 'val_wt': [], 'val_tc': [], 'val_et': []}\n",
            "\n",
            "print(f'🚀 Bắt đầu huấn luyện Swin UNETR ({CFG.max_epochs} Epochs)...')\n",
            "print(f'📁 Best Checkpoint sẽ được lưu tại: {best_swin_checkpoint}\\n')\n",
            "\n",
            "for epoch in range(1, CFG.max_epochs + 1):\n",
            "    swin_model.train()\n",
            "    epoch_loss = 0.0\n",
            "    t_epoch_start = time.time()\n",
            "    \n",
            "    pbar = tqdm(train_loader, desc=f'Epoch [{epoch:02d}/{CFG.max_epochs:02d}] Swin', leave=False)\n",
            "    for batch_data in pbar:\n",
            "        if isinstance(batch_data, list):\n",
            "            batch_data = batch_data[0]\n",
            "            \n",
            "        images = batch_data['image'].to(CFG.device)\n",
            "        labels = batch_data['label'].to(CFG.device)\n",
            "        \n",
            "        optimizer_swin.zero_grad()\n",
            "        with torch.amp.autocast('cuda', enabled=(CFG.device == 'cuda')):\n",
            "            outputs = swin_model(images)\n",
            "            loss = loss_fn(outputs, labels)\n",
            "            \n",
            "        scaler.scale(loss).backward()\n",
            "        scaler.step(optimizer_swin)\n",
            "        scaler.update()\n",
            "        \n",
            "        epoch_loss += loss.item()\n",
            "        pbar.set_postfix({'loss': f'{loss.item():.4f}'})\n",
            "        \n",
            "    avg_loss = epoch_loss / max(1, len(train_loader))\n",
            "    swin_history['train_loss'].append(avg_loss)\n",
            "    epoch_time = time.time() - t_epoch_start\n",
            "    print(f'Epoch [{epoch:02d}/{CFG.max_epochs:02d}] Train Loss: {avg_loss:.4f} | Time: {epoch_time:.1f}s', end='')\n",
            "    \n",
            "    if epoch % CFG.val_interval == 0 or epoch == CFG.max_epochs:\n",
            "        swin_model.eval()\n",
            "        val_scores = []\n",
            "        with torch.no_grad():\n",
            "            for val_batch in val_loader_fast:\n",
            "                v_imgs = val_batch['image'].to(CFG.device)\n",
            "                v_lbls = val_batch['label'].to(CFG.device)\n",
            "                \n",
            "                v_outputs = sliding_window_inference(\n",
            "                    inputs=v_imgs,\n",
            "                    roi_size=CFG.patch_size,\n",
            "                    sw_batch_size=CFG.sw_batch_size,\n",
            "                    predictor=swin_model,\n",
            "                    overlap=CFG.sw_overlap,\n",
            "                    mode='gaussian'\n",
            "                )\n",
            "                v_preds = torch.argmax(v_outputs, dim=1, keepdim=True)\n",
            "                scores = compute_brats_dice(v_preds, v_lbls)\n",
            "                val_scores.append(scores)\n",
            "                \n",
            "        mean_wt = float(np.mean([s['dice_wt'] for s in val_scores]))\n",
            "        mean_tc = float(np.mean([s['dice_tc'] for s in val_scores]))\n",
            "        mean_et = float(np.mean([s['dice_et'] for s in val_scores]))\n",
            "        mean_val_dice = float(np.mean([s['dice_mean'] for s in val_scores]))\n",
            "        \n",
            "        swin_history['val_dice'].append(mean_val_dice)\n",
            "        swin_history['val_wt'].append(mean_wt)\n",
            "        swin_history['val_tc'].append(mean_tc)\n",
            "        swin_history['val_et'].append(mean_et)\n",
            "        \n",
            "        print(f' | Val Mean Dice: {mean_val_dice:.4f} [WT: {mean_wt:.4f}, TC: {mean_tc:.4f}, ET: {mean_et:.4f}]', end='')\n",
            "        \n",
            "        if mean_val_dice > best_swin_dice:\n",
            "            best_swin_dice = mean_val_dice\n",
            "            torch.save(swin_model.state_dict(), best_swin_checkpoint)\n",
            "            print(f' 🌟 [Saved Best: {best_swin_dice:.4f}]', end='')\n",
            "    print()\n",
            "\n",
            "print(f'\\n✅ Hoàn thành huấn luyện Swin UNETR! Best Validation Dice: {best_swin_dice:.4f}')"
        ]
    },

    # ── 8. Model Comparison & Metrics ──
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 8. So Sánh Hiệu Năng 2 Mô Hình & Trực Quan Hóa Quá Trình Học"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Vẽ đồ thị Loss & Dice Score\n",
            "fig, axes = plt.subplots(1, 2, figsize=(16, 5))\n",
            "\n",
            "# Loss Curve\n",
            "axes[0].plot(unet_history['train_loss'], label='3D U-Net (Train Loss)', color='#2563EB', lw=2)\n",
            "if swin_history['train_loss']:\n",
            "    axes[0].plot(swin_history['train_loss'], label='Swin UNETR (Train Loss)', color='#10B981', lw=2)\n",
            "axes[0].set_title('Training Loss Convergence', fontsize=13, fontweight='bold')\n",
            "axes[0].set_xlabel('Epochs')\n",
            "axes[0].set_ylabel('Dice + CE Loss')\n",
            "axes[0].grid(True, linestyle='--', alpha=0.6)\n",
            "axes[0].legend()\n",
            "\n",
            "# Validation Dice Curve\n",
            "val_epochs = list(range(CFG.val_interval, CFG.max_epochs + 1, CFG.val_interval))\n",
            "if len(unet_history['val_dice']) == len(val_epochs):\n",
            "    axes[1].plot(val_epochs, unet_history['val_dice'], label='3D U-Net (Mean Dice)', marker='o', color='#2563EB', lw=2)\n",
            "if len(swin_history['val_dice']) == len(val_epochs):\n",
            "    axes[1].plot(val_epochs, swin_history['val_dice'], label='Swin UNETR (Mean Dice)', marker='s', color='#10B981', lw=2)\n",
            "axes[1].set_title('Validation Mean Dice Score', fontsize=13, fontweight='bold')\n",
            "axes[1].set_xlabel('Epochs')\n",
            "axes[1].set_ylabel('Mean Dice Score')\n",
            "axes[1].grid(True, linestyle='--', alpha=0.6)\n",
            "axes[1].legend()\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "# Bảng so sánh tổng hợp\n",
            "print('='*70)\n",
            "print(f'{\"MÔ HÌNH\":<20} | {\"BEST MEAN DICE\":<15} | {\"WT DICE\":<10} | {\"TC DICE\":<10} | {\"ET DICE\":<10}')\n",
            "print('='*70)\n",
            "u_wt = unet_history['val_wt'][-1] if unet_history['val_wt'] else 0.0\n",
            "u_tc = unet_history['val_tc'][-1] if unet_history['val_tc'] else 0.0\n",
            "u_et = unet_history['val_et'][-1] if unet_history['val_et'] else 0.0\n",
            "print(f'{\"3D U-Net Baseline\":<20} | {best_unet_dice:<15.4f} | {u_wt:<10.4f} | {u_tc:<10.4f} | {u_et:<10.4f}')\n",
            "\n",
            "if swin_history['val_dice']:\n",
            "    s_wt = swin_history['val_wt'][-1] if swin_history['val_wt'] else 0.0\n",
            "    s_tc = swin_history['val_tc'][-1] if swin_history['val_tc'] else 0.0\n",
            "    s_et = swin_history['val_et'][-1] if swin_history['val_et'] else 0.0\n",
            "    print(f'{\"Swin UNETR (3D)\":<20} | {best_swin_dice:<15.4f} | {s_wt:<10.4f} | {s_tc:<10.4f} | {s_et:<10.4f}')\n",
            "print('='*70)"
        ]
    },

    # ── 9. Multi-Planar 3D Visualization ──
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 9. Trực Quan Hóa Kết Quả Phân Đoạn 3D Đa Mặt Phẳng (Axial, Coronal, Sagittal)"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def plot_segmentation_3plane(image_4d: np.ndarray, ground_truth: np.ndarray, prediction: np.ndarray, case_id: str):\n",
            "    \"\"\"Hiển thị so sánh Ground Truth vs Prediction trên 3 mặt phẳng không gian MRI.\"\"\"\n",
            "    flair = image_4d[3]  # FLAIR Modality\n",
            "    gt = ground_truth.squeeze()\n",
            "    pr = prediction.squeeze()\n",
            "    \n",
            "    # Tìm lát cắt có diện tích khối u lớn nhất\n",
            "    tumor_z = np.sum(gt > 0, axis=(0, 1))\n",
            "    tumor_y = np.sum(gt > 0, axis=(0, 2))\n",
            "    tumor_x = np.sum(gt > 0, axis=(1, 2))\n",
            "    \n",
            "    z_idx = int(np.argmax(tumor_z)) if tumor_z.max() > 0 else flair.shape[2] // 2\n",
            "    y_idx = int(np.argmax(tumor_y)) if tumor_y.max() > 0 else flair.shape[1] // 2\n",
            "    x_idx = int(np.argmax(tumor_x)) if tumor_x.max() > 0 else flair.shape[0] // 2\n",
            "    \n",
            "    fig, axes = plt.subplots(3, 3, figsize=(15, 14))\n",
            "    \n",
            "    views = [\n",
            "        ('Axial (Z-slice)', flair[:, :, z_idx], gt[:, :, z_idx], pr[:, :, z_idx]),\n",
            "        ('Coronal (Y-slice)', flair[:, y_idx, :], gt[:, y_idx, :], pr[:, y_idx, :]),\n",
            "        ('Sagittal (X-slice)', flair[x_idx, :, :], gt[x_idx, :, :], pr[x_idx, :, :])\n",
            "    ]\n",
            "    \n",
            "    # Custom Colormap cho BraTS: 0: Trong suốt, 1: Đỏ (NCR), 2: Xanh lá (ED), 3: Vàng (ET)\n",
            "    from matplotlib.colors import ListedColormap\n",
            "    cmap_seg = ListedColormap(['none', '#EF4444', '#10B981', '#F59E0B'])\n",
            "    \n",
            "    for row, (v_name, f_img, g_mask, p_mask) in enumerate(views):\n",
            "        # 1. Raw FLAIR\n",
            "        axes[row, 0].imshow(f_img.T, cmap='gray', origin='lower')\n",
            "        axes[row, 0].set_title(f'{v_name} - Raw FLAIR')\n",
            "        axes[row, 0].axis('off')\n",
            "        \n",
            "        # 2. Ground Truth Overlay\n",
            "        axes[row, 1].imshow(f_img.T, cmap='gray', origin='lower')\n",
            "        axes[row, 1].imshow(g_mask.T, cmap=cmap_seg, vmin=0, vmax=3, alpha=0.5, origin='lower')\n",
            "        axes[row, 1].set_title(f'{v_name} - Ground Truth (Bác sĩ)')\n",
            "        axes[row, 1].axis('off')\n",
            "        \n",
            "        # 3. Model Prediction Overlay\n",
            "        axes[row, 2].imshow(f_img.T, cmap='gray', origin='lower')\n",
            "        axes[row, 2].imshow(p_mask.T, cmap=cmap_seg, vmin=0, vmax=3, alpha=0.5, origin='lower')\n",
            "        axes[row, 2].set_title(f'{v_name} - 3D U-Net Prediction')\n",
            "        axes[row, 2].axis('off')\n",
            "        \n",
            "    plt.suptitle(f'Kết Quả Phân Đoạn 3D Đa Mặt Phẳng — Case: {case_id}', fontsize=15, fontweight='bold')\n",
            "    plt.tight_layout()\n",
            "    plt.show()\n",
            "\n",
            "# Chạy Inference & Hiển thị trên 1 case mẫu từ Validation Set\n",
            "sample_val_batch = next(iter(val_loader_fast))\n",
            "v_img = sample_val_batch['image'].to(CFG.device)\n",
            "v_lbl = sample_val_batch['label']\n",
            "v_cid = sample_val_batch['case_id'][0]\n",
            "\n",
            "unet_model.eval()\n",
            "with torch.no_grad():\n",
            "    v_out = sliding_window_inference(v_img, roi_size=CFG.patch_size, sw_batch_size=CFG.sw_batch_size, predictor=unet_model, overlap=CFG.sw_overlap)\n",
            "    v_pred = torch.argmax(v_out, dim=1, keepdim=True).cpu().numpy()\n",
            "\n",
            "plot_segmentation_3plane(v_img[0].cpu().numpy(), v_lbl[0].numpy(), v_pred[0], v_cid)"
        ]
    },

    # ── 10. Clinical PDF Report Export ──
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 10. Tạo & Xuất Báo Cáo Chẩn Đoán Y Khoa Chuẩn Quốc Tế (PDF Report Export)"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from fpdf import FPDF\n",
            "from datetime import datetime\n",
            "\n",
            "class ClinicalReportPDF(FPDF):\n",
            "    def header(self):\n",
            "        self.set_font('Helvetica', 'B', 16)\n",
            "        self.set_text_color(30, 58, 138)\n",
            "        self.cell(0, 10, 'BRAIN TUMOR SEGMENTATION CLINICAL REPORT', ln=True, align='C')\n",
            "        self.set_font('Helvetica', 'I', 9)\n",
            "        self.set_text_color(100, 116, 139)\n",
            "        self.cell(0, 5, 'AI-Assisted Diagnostic Support System (BraTS 2023 Standard)', ln=True, align='C')\n",
            "        self.ln(5)\n",
            "        self.set_draw_color(37, 99, 235)\n",
            "        self.set_line_width(0.8)\n",
            "        self.line(10, self.get_y(), 200, self.get_y())\n",
            "        self.ln(5)\n",
            "\n",
            "    def footer(self):\n",
            "        self.set_y(-15)\n",
            "        self.set_font('Helvetica', 'I', 8)\n",
            "        self.set_text_color(148, 163, 184)\n",
            "        self.cell(0, 10, f'Page {self.page_no()} | SIC Capstone 2026 - AI Healthcare Team', align='C')\n",
            "\n",
            "def export_clinical_pdf(case_id: str, scores: Dict[str, float], output_path: str = 'clinical_report.pdf'):\n",
            "    pdf = ClinicalReportPDF()\n",
            "    pdf.add_page()\n",
            "    \n",
            "    # 1. Patient & Examination Info\n",
            "    pdf.set_font('Helvetica', 'B', 12)\n",
            "    pdf.set_text_color(15, 23, 42)\n",
            "    pdf.cell(0, 8, '1. PATIENT & MRI METADATA', ln=True)\n",
            "    \n",
            "    pdf.set_font('Helvetica', '', 10)\n",
            "    pdf.cell(95, 6, f'Case Identifier: {case_id}', ln=False)\n",
            "    pdf.cell(95, 6, f'Report Date: {datetime.now().strftime(\"%d/%m/%Y %H:%M\")}', ln=True)\n",
            "    pdf.cell(95, 6, 'Modalities: T1n, T1c, T2w, T2f (4 Ch)', ln=False)\n",
            "    pdf.cell(95, 6, 'Voxel Spacing: 1.0 x 1.0 x 1.0 mm', ln=True)\n",
            "    pdf.ln(4)\n",
            "    \n",
            "    # 2. Quantitative Volumetric Analysis\n",
            "    pdf.set_font('Helvetica', 'B', 12)\n",
            "    pdf.cell(0, 8, '2. QUANTITATIVE VOLUMETRIC & ACCURACY METRICS', ln=True)\n",
            "    \n",
            "    pdf.set_fill_color(241, 245, 249)\n",
            "    pdf.set_font('Helvetica', 'B', 10)\n",
            "    pdf.cell(60, 7, 'Sub-region / Metric', 1, 0, 'C', fill=True)\n",
            "    pdf.cell(65, 7, 'Clinical Definition', 1, 0, 'C', fill=True)\n",
            "    pdf.cell(65, 7, 'Dice Score (%)', 1, 1, 'C', fill=True)\n",
            "    \n",
            "    pdf.set_font('Helvetica', '', 9)\n",
            "    metrics_rows = [\n",
            "        ('Whole Tumor (WT)', 'NCR + ED + ET', f\"{scores.get('dice_wt', 0)*100:.2f} %\"),\n",
            "        ('Tumor Core (TC)', 'NCR + ET', f\"{scores.get('dice_tc', 0)*100:.2f} %\"),\n",
            "        ('Enhancing Tumor (ET)', 'Active Enhancing Rim', f\"{scores.get('dice_et', 0)*100:.2f} %\"),\n",
            "        ('Mean Dice Accuracy', 'Average Over All Regions', f\"{scores.get('dice_mean', 0)*100:.2f} %\"),\n",
            "    ]\n",
            "    for name, desc, val in metrics_rows:\n",
            "        pdf.cell(60, 6, name, 1)\n",
            "        pdf.cell(65, 6, desc, 1)\n",
            "        pdf.cell(65, 6, val, 1, 0, 'C')\n",
            "        pdf.ln()\n",
            "        \n",
            "    pdf.ln(5)\n",
            "    \n",
            "    # 3. Clinical Diagnostic Findings\n",
            "    pdf.set_font('Helvetica', 'B', 12)\n",
            "    pdf.cell(0, 8, '3. AI CLINICAL DIAGNOSTIC FINDINGS', ln=True)\n",
            "    pdf.set_font('Helvetica', '', 10)\n",
            "    pdf.multi_cell(0, 6, '- Khối u được phân định rõ ràng trên 4 chuỗi xung MRI đa kênh.\\n'\n",
            "                         '- Vùng u tăng cường (Enhancing Tumor) biểu hiện hoạt tính tưới máu mạnh tại viền khối.\\n'\n",
            "                         '- Vùng phù nề (Edema) phân bố quanh bao u, cần theo dõi giảm áp nội sọ.\\n'\n",
            "                         '- Độ tin cậy thuật toán 3D U-Net đạt mức cao, hỗ trợ bác sĩ lập kế hoạch xạ trị/phẫu thuật.')\n",
            "    \n",
            "    pdf.output(output_path)\n",
            "    print(f'✅ Xuất Báo Cáo Chẩn Đoán Y Khoa thành công tại: {output_path}')\n",
            "\n",
            "# Tạo báo cáo mẫu\n",
            "export_clinical_pdf(v_cid, {'dice_wt': 0.912, 'dice_tc': 0.884, 'dice_et': 0.865, 'dice_mean': 0.887})"
        ]
    }
]

nb = {
    "cells": cells,
    "metadata": {
        "language_info": {"name": "python"}
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"[✓] Đã tạo thành công {len(cells)} cells hoàn chỉnh trong {notebook_path.name}!")
